name: update RRP data
on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build & Run"
        run: |
          ls .
          pwd
          npm install
          node backend/index.js
          echo "hello.."
